"""make debtor_id nullable

Revision ID: be81b259ef2e
Revises: 3db85614360b
Create Date: 2025-11-22 18:04:39.155581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be81b259ef2e'
down_revision: Union[str, Sequence[str], None] = '3db85614360b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'debtor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'debtor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
